version: '3.1'

services:
  nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - reverse-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.SWQ_API.rule=Host(`api.sign.quiches.ovh`)
      - traefik.http.routers.SWQ_API.entrypoints=http
      - traefik.http.routers.SWQ_API.middlewares=https-redirect@file
      - traefik.http.routers.SWQ_API-Https.rule=Host(`api.sign.quiches.ovh`)
      - traefik.http.routers.SWQ_API-Https.entrypoints=https
      - traefik.http.routers.SWQ_API-Https.middlewares=security@file, compression@file
      - traefik.http.routers.SWQ_API-Https.tls=true
      - traefik.http.routers.SWQ_API-Https.tls.certresolver=letsencrypt

networks:
  reverse-proxy:
    external: true
